### ISSUE TITLE
Table config should allow exclude/blacklist property

### ISSUE THREAD

**Issue by timwis** [timwis/vizwit#123]
For datasets with tons of columns, rather than explicitly listing each one you want, list the ones you don't want

**Comment by marks** [comment]
@timwis is this what you were thinking of?

card config called `columnsToHide` (example: https://gist.github.com/marks/cf635692f034e9a81c16#file-chicago-crimes-v2-json-L96)
> 		"columnsToHide":["id","x_coordinate","y_coordinate"]

demo: http://marks.github.io/vizwit/?gist=cf635692f034e9a81c16

**Comment by timwis** [comment]
exactly!

**Comment by marks** [comment]
Cool - just created https://github.com/timwis/vizwit/pull/142

**Comment by timwis** [comment]
Merged! Do you have access to add this to the wiki page on configuration?

**Comment by marks** [comment]
@timwis yup! Added here (https://github.com/timwis/vizwit/wiki/Configuration#table-display-options) - feel free to move or let me know if anything else is needed

**Comment by timwis** [comment]
Thanks!
