### ISSUE TITLE
add option to abbreviate call out card number ($214,210,124,241 => $214 billion)

### ISSUE THREAD

**Issue by marks** [timwis/vizwit#167]
Example: 
![medicaid_drug_utilization_data_-_vizwit](https://cloud.githubusercontent.com/assets/34566/12815184/942361a4-cb12-11e5-8cad-24fefbfc7542.png)

**Comment by timwis** [comment]
@marks this is available already via [valueFormat](https://github.com/timwis/vizwit/wiki/Configuration#valueformat) ([example](https://gist.github.com/timwis/eec2c0f438ebc8fd67c6)). Or am I misunderstanding? (If so, re-open)
