### ISSUE TITLE
Exporting table should export all results, not just the table limit

### ISSUE THREAD

**Issue by marks** [timwis/vizwit#168]

**Comment by marks** [comment]
@timwis is adding the following to `views/table.js` the _right_ way to do this?
```
  updateExportLink: function (collection) {
    collection = collection || this.collection
    collection.config.limit = parseInt(collection.recordCount)
    this.$('.export-link').attr('href', collection.exportUrl())
  }
```

**Comment by timwis** [comment]
Hey @marks sorry for my delay. Good catch with this!

Let me know if I'm overlooking anything, but I think this logic should probably live in the provider's [`exportUrl`](https://github.com/timwis/vizwit/blob/master/src/scripts/collections/socrata.js#L66) method since "getting all records" may be provider-specific. Something like:
```javascript
  exportUrl: function () {
    var oldLimit = this.config.limit
    this.config.limit = null
    var exportUrl = this.url().replace(this.config.dataset + '.json', this.config.dataset + '.csv')
    this.config.limit = oldLimit
    return exportUrl
  }
```

**Comment by marks** [comment]
@timwis very good point. I'll look into submitting a patch for the Socrata provider tonight

**Comment by marks** [comment]
@timwis why not just:

```
exportUrl: function () {
    this.config.limit = null
    var exportUrl = this.url().replace(this.config.dataset + '.json', this.config.dataset + '.csv')
    return exportUrl
},

```

**Comment by timwis** [comment]
Thanks for the PR @marks! If I recall correctly, the reason we want to set `this.config.limit` back to its original value is because if you clicked "export" and then tried to paginate the table, you'd get a thousand rows instead of the intended 10 (since export works off the table's model).

**Comment by marks** [comment]
Ah, got it. Thanks!
