### ISSUE TITLE
Table text search results paging issue

### ISSUE THREAD

**Issue by shua123** [timwis/vizwit#175]
When using the table search box the results count and page links do not seem to be updating.

(using http://vizw.it/?gist=a304ce8fac9c14dfbf16)
![image](https://cloud.githubusercontent.com/assets/1593537/14574213/d22e3bc8-031f-11e6-83cb-49202710bf60.png)

Working example when filtering through another card:
![image](https://cloud.githubusercontent.com/assets/1593537/14574284/43147adc-0320-11e6-9696-821fea021802.png)

**Comment by marks** [comment]
@shua123 I see that too.. thanks for logging the bug. I found a fix (see commit above) but I'm not sure if it's the most efficient or "the right way" so need to defer to @timwis for his expertise.

Demo:

![um4txgkosa](https://cloud.githubusercontent.com/assets/34566/14583794/f5a2bf08-03fa-11e6-9795-53fc9329d10f.gif)

**Comment by timwis** [comment]
Thanks for reporting @shua123! @marks, looks like you've got it fixed. Do you mind submitting a PR?

**Comment by marks** [comment]
PR: https://github.com/timwis/vizwit/pull/180
